POST http://localhost:8080/server_Web_exploded/api/actions?action=start
Content-Type: application/json

{
  "timetableID": 0,
  "engineSettings": {
    "populationSize": 32,
    "selection": {
      "name": "rouletteWheel"
    },
    "elitism": 0,
    "crossover": {
      "name": "datetimeOriented",
      "cuttingPoints": 5
    },
    "mutations": [
      {
        "name": "flipping",
        "probability": 0.2,
        "maxTupples": 3,
        "component": "H"
      }
    ]
  },
  "stride": 2,
  "endPredicates": [
    {
      "name": "numOfGeneration",
      "value": 300
    },
    {
      "name": "fitnessScore",
      "value": 87.9
    },
    {
      "name": "time",
      "value": 39
    }
  ]
}

###
GET http://localhost:8080/server_Web_exploded/api/timetable/details?timetableid=0
Accept: application/json

###
POST http://localhost:8080/server_Web_exploded/login
Content-Type: application/json

{
  "key": "value"
}

<> 2021-09-21T183852.404.html

###


###
POST http://localhost:8080/server_Web_exploded/login
Accept: application/json
{}


###
GET http://localhost:8080/server_Web_exploded/
Accept: application/json

<> 2021-09-21T183418.200.html
<> 2021-09-21T181458.200.html
<> 2021-09-21T164722.200.html

###
POST http://localhost:8080/server_Web_exploded/login?username=cupcake
Accept: application/json

